### ISSUE TITLE
Horizontal line (hr)

### ISSUE THREAD

**Issue by Pareder** [cloverhearts/quilljs-markdown#63]
Is it possible to parse [markdown horizontal rules](https://www.markdownguide.org/basic-syntax/#horizontal-rules)?

There are such dividers in [QuillJS](https://quilljs.com/guides/cloning-medium-with-parchment/#dividers) and I want `***` or `---` to work correctly. But currently `---` is not supported at all and `***` throws error:
```
quill.js:1449 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at t.value (quill.js:1449:30)
    at index.js:43:24
```
You can try it on [demo site](https://cloverhearts.github.io/quilljs-markdown/).

So the question is how to make it work?

**Comment by cloverhearts** [comment]
Hmm i will check it.
